dictionnary/urls.py
from django.urls import path
from dictionnary import views

app_name = 'dictionnary'

urlpatterns = [
    path('createword/', views.WordCreateView.as_view(), name='createword'),
    path('listword/', views.WordListView.as_view(), name='listword'),
    path('updateword/<int:pk>', views.WordUpdateView.as_view(), name='updateword'),
    path('detailword/<int:pk>', views.WordDetailView.as_view(), name='detailword'),
    path('searchword/',views.search_word,name='searchword'),
	path('deleteword/<int:pk>',views.WordDeleteView.as_view(),name='deleteword'),
]

generator/urls.py
from django.urls import path
from generator import views

app_name = 'generator'

urlpatterns = [
    path('', views.generator_form_view, name='setgenerator'),
]

morwuwhw_dict/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dictionnary/', include('dictionnary.urls')),
    path('generator/', include('generator.urls')),
]

dictionnary/models.py
from django.db import models
from django.urls import reverse
from django.utils.timezone import now

class Word(models.Model):
    morwuwhw = models.CharField(null=False,blank=False,max_length=50)
    french = models.CharField(null=False,blank=False,max_length=50)
    precisions = models.TextField(null=False,blank=True)
    entry_date = models.DateField(default=now)

    def __str__(self):
        return self.french + " : " + self.morwuwhw + " (" + self.precisions[0:10] + ")"

    def get_absolute_url(self):
        return reverse("dictionnary:createword",kwargs={})

dictionnary/forms.py
from django import forms
from django.core.validators import RegexValidator

class SearchWordForm(forms.Form):
    FRANCAIS = 'FR'
    MORWUWHW = 'MH'
    LANGUAGES = (
        (FRANCAIS, 'Français'),
        (MORWUWHW, 'Morwuwhw'),
    )

    alphanumeric = RegexValidator(
        regex=r'^[a-zàáâãäåòóôõöèéêëçìíîïùúûüÿ]*$',
        message='Votre mot ne doit contenir que des lettres minuscules'
    )

    word = forms.CharField(max_length=50,validators=[alphanumeric])
    language = forms.ChoiceField(choices=LANGUAGES)

dictionnary/views.py
from django.shortcuts import render
from django.http import Http404
from django.utils.translation import ugettext as _
from django.views.generic.edit import FormMixin
from dictionnary.models import Word
from dictionnary.forms import SearchWordForm
#from dictionnary.forms import SearchForm
from django.urls import reverse_lazy
from django.views.generic import (CreateView,
									ListView,
									DetailView,
									DeleteView,
									UpdateView)
import logging
import csv

logging.basicConfig(level=logging.DEBUG)
_logger = logging.getLogger(__name__)

class FormListView(FormMixin, ListView):
	def get(self, request, *args, **kwargs):
		# From ProcessFormMixin
		form_class = self.get_form_class()
		self.form = self.get_form(form_class)

		# From BaseListView
		self.object_list = self.get_queryset()
		allow_empty = self.get_allow_empty()
		if not allow_empty and len(self.object_list) == 0:
			raise Http404(_(u"Empty list and '%(class_name)s.allow_empty' is False.")
						  % {'class_name': self.__class__.__name__})

		context = self.get_context_data(object_list=self.object_list, form=self.form)
		return self.render_to_response(context)

	def post(self, request, *args, **kwargs):
		return self.get(request, *args, **kwargs)

class WordCreateView(CreateView):
	fields = ('french','morwuwhw','precisions')
	model = Word
	template_name = 'dictionnary/word_create_view.html'
	success_url = reverse_lazy("dictionnary:listword")

class WordListView(FormListView):
	form_class = SearchWordForm
	model = Word
	template_name = 'dictionnary/word_list_view.html'
	queryset = Word.objects.all().order_by('morwuwhw')

	def load_file_data(self):
		with open('../saved_data/words-data.csv') as f:
				reader = csv.reader(f)

				for row in reader:
					_logger.debug("french: {}, morwuwhw: {}, description: {}".format(row[0],row[1],row[2]))
					_, created = Word.objects.get_or_create(
						french=row[0],
						morwuwhw=row[1],
						description=row[2],
						)
					# creates a tuple of the new object or
					# current object and a boolean of if it was created

class WordDetailView(DetailView):
	model = Word
	template_name = 'dictionnary/word_detail_view.html'

class WordUpdateView(UpdateView):
	fields = ('french','morwuwhw','precisions')
	model = Word
	template_name = 'dictionnary/word_update_view.html'
	success_url = reverse_lazy("dictionnary:listword")

class WordDeleteView(DeleteView):
	model = Word
	success_url = reverse_lazy("dictionnary:listword")
	template_name = 'dictionnary/word_delete_view.html'

def search_word(request):
	search_form = SearchWordForm()

	if request.method == 'POST':
		search_form = SearchWordForm(request.POST)

		if search_form.is_valid():
			result = None
			if search_form.cleaned_data['language'] == SearchWordForm.MORWUWHW:
				result = Word.objects.filter(morwuwhw=search_form.cleaned_data['word']).order_by('morwuwhw')
			elif search_form.cleaned_data['language'] == SearchWordForm.FRANCAIS:
				result = Word.objects.filter(french=search_form.cleaned_data['word']).order_by('french')
			else:
				return render(request,'dictionnary/word_list_view.html')

			if len(result) == 0:
				if search_form.cleaned_data['language'] == SearchWordForm.MORWUWHW:
					result = Word.objects.filter(morwuwhw__icontains=search_form.cleaned_data['word']).order_by('morwuwhw')
				elif search_form.cleaned_data['language'] == SearchWordForm.FRANCAIS:
					result = Word.objects.filter(french__icontains=search_form.cleaned_data['word']).order_by('french')
				else:
					return render(request,'dictionnary/word_list_view.html')

			return render(request,'dictionnary/search_result.html',{'word_list':result})
		else:
			return render(request,'dictionnary/word_list_view.html')

dictionnary/templates/dictionnary/search_result.html
{% extends "morwuwhw_dict/dict_base.html" %}

{% block body_block %}
  <p>Votre recherche à donner {{ word_list|length }} candidats.</p>
  <div class="container btn btn-primary">
    <a href="{% url 'dictionnary:listword' %}">Retour</a>
  </div>
  <table>
    <tr class="tab-header">
      <th>Français</th>
      <th>Morwuwhw</th>
      <th>Précisions</th>
    </tr>
    {% for word in word_list %}
    <tr class="tab-rows">
      <th><a href="{% url 'dictionnary:detailword' pk=word.pk %}">{{ word.french }}</a></th>
      <th><a href="{% url 'dictionnary:detailword' pk=word.pk %}">{{ word.morwuwhw }}</a></th>
      <th>{{ word.precisions }}</th>
    </tr>
    {% endfor %}
  </table>
{% endblock %}

dictionnary/templates/dictionnary/word_create_view.html
{% extends "morwuwhw_dict/dict_base.html" %}

{% block body_block %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Ajouter">
  </form>
{% endblock %}

dictionnary/templates/dictionnary/word_delete_view.html
{% extends "morwuwhw_dict/dict_base.html" %}

{% block body_block %}
<form method="post">{% csrf_token %}
  <p>Étes-vous sûr de vouloir supprimer l’entrée : "{{ object }}" ?</p>
  <input class="btn btn-primary btn-danger" type="submit" value="Supprimer">
</form>
{% endblock %}

dictionnary/templates/dictionnary/word_detail_view.html
{% extends "morwuwhw_dict/dict_base.html" %}

{% block body_block %}
<table>
  <tr class="tab-header">
    <th>Français</th>
    <th>Morwuwhw</th>
    <th>Précisions</th>
  </tr>
  <tr class="tab-rows">
    <th><a href="{% url 'dictionnary:detailword' pk=word.pk %}">{{ word.french }}</a></th>
    <th><a href="{% url 'dictionnary:detailword' pk=word.pk %}">{{ word.morwuwhw }}</a></th>
    <th>{{ word.precisions }}</th>
  </tr>
</table>
<div class="container buttons">
  <a href="{% url 'dictionnary:listword' %}" class="btn btn-primary">Retour</a>
  <a href="{% url 'dictionnary:updateword' pk=word.pk %}" class="btn btn-primary">Éditer</a>
	<a href="{% url 'dictionnary:deleteword' pk=word.pk %}" class="btn btn-primary btn-danger">Supprimer</a>
</div>
{% endblock %}

dictionnary/templates/dictionnary/word_list_view.html
{% extends "morwuwhw_dict/dict_base.html" %}

{% block body_block %}
  <p>Le dictionnaire contient actuellement {{ word_list|length }} mots.</p>
  <div class="container buttons">
    <div class="row">
      <div class="col-sm-6">
        <a href="{% url 'dictionnary:createword' %}" class="btn btn-primary add-btn">Ajouter un mot</a>
      </div>
      <div class="col-sm-6">
        <form class="search-form" method="post" action="{% url 'dictionnary:searchword' %}">
          {% csrf_token %}
          {{ form.as_p }}
          <input class="btn btn-primary" type="submit" value="Chercher">
        </form>
      </div>
    </div>
  </div>
  <table>
    <tr class="tab-header">
      <th>Français</th>
      <th>Morwuwhw</th>
      <th>Précisions</th>
    </tr>
    {% for word in word_list %}
    <tr class="tab-rows">
      <th><a href="{% url 'dictionnary:detailword' pk=word.pk %}">{{ word.french }}</a></th>
      <th><a href="{% url 'dictionnary:detailword' pk=word.pk %}">{{ word.morwuwhw }}</a></th>
      <th>{{ word.precisions }}</th>
    </tr>
    {% endfor %}
  </table>
{% endblock %}

dictionnary/templates/dictionnary/word_update_view.html
{% extends "morwuwhw_dict/dict_base.html" %}

{% block body_block %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input class="btn btn-primary" type="submit" value="Valider">
  <a href="{% url 'dictionnary:listword' %}" class="btn btn-primary">Retour</a>
</form>
{% endblock %}