dictionnary/urls.py
from django.urls import path
from dictionnary import views

app_name = 'dictionnary'

urlpatterns = [
    path('createword/', views.WordCreateView.as_view(), name='createword'),
    path('listword/', views.WordListView.as_view(), name='listword'),
    path('updateword/<int:pk>', views.WordUpdateView.as_view(), name='updateword'),
    path('detailword/<int:pk>', views.WordDetailView.as_view(), name='detailword'),
    path('searchword/',views.search_word,name='searchword'),
	path('deleteword/<int:pk>',views.WordDeleteView.as_view(),name='deleteword'),
]

generator/urls.py
from django.urls import path
from generator import views

app_name = 'generator'

urlpatterns = [
    path('', views.generator_form_view, name='setgenerator'),
]

morwuwhw_dict/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dictionnary/', include('dictionnary.urls')),
    path('generator/', include('generator.urls')),
]

templates/morwuwhw_dict/dict_base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>

<head>
  {% block pagetitle %}
    <title>Dictionnaire : Français - Morwuwhw</title>
  {% endblock %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="content-type" content="text/html; charset=windows-1252" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'css/style.css'%}" />

  {% block additionnal_css %}
  {% endblock %}

  {% block additional_scripts %}
  {% endblock %}
</head>

<body>

<section id="navbar_section">
  <nav class="navbar navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          Menu <span class="glyphicon glyphicon-chevron-down"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse navbar-right" id="myNavbar">
        <ul class="nav navbar-nav" id="nav">
          <li><a href="{% url 'dictionnary:listword' %}">Liste</a></li>
          <li><a href="{% url 'generator:setgenerator' %}">Générateur</a></li>
        </ul>
      </div>
    </div>
  </nav>
</section>

<section id="content_section">
  <div class="container text-justify">
    {% block body_block %}
    {% endblock %}
  </div>
</section>

</body>
</html>